language: php

php:
 - 7.2
 - 7.3
 - 7.4
 
sudo: false
dist: trusty

install:
- "wget -O - https://poggit.pmmp.io/res/travisInstall.sh | bash -s - || true"

script:
- "if [ -f ${TRAVIS_BUILD_DIR}/../PocketMine/unstaged/XPShop.phar ] ; then wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - XPShop XPShop ; else true ; fi"
