name: XPShop
author: MintoD
version: 1.1.0
description: Buy and sell XP
api: [3.0.0]
main: MintoD\XPShop\Main

commands:
  xpshop:
    description: XP Shop
    permission: xpshop.cmd

permissions:
  xpshop.cmd:
    description: Allow players to use XPShop command
    default: op
