title: XP Shop
sell_button: Sell
buy_button: Buy

sell_title: Sell XP
sell_slider_label: Please choose XP to sell

buy_title: Buy EXP
buy_slider_label: Please choose XP to buy

xpPriceWhenSell: 10 # 1 XP level = 10$ when sell
xpPriceWhenBuy: 9 # 1 XP level = 9$ when buy

sellSuccess: Sold!
buySuccess: Bought!

doNotEnoughMoney: You don't have enough money
isNotANumber: XP must be number
